@Library('service-bridge-jenkins-shared-library') _

pipeline {
    agent any

    environment {
        BRANCH = 'main'
        CREDENTIALS_ID = 'github-security-passcode'
        REPO_URL = 'https://github.com/MrDeyi/main-app.git'
    }

    tools {
        maven 'Maven:3.9.1'
    }

    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }

        stage("Clone Repo") {
            steps {
                cloneRepo(BRANCH, CREDENTIALS_ID, REPO_URL)
            }
        }

        stage("Trigger Test Pipeline") {
            steps {
                dir('Main_app') {
                    sh ' mvn -Dtest=CucumberTestRunner test'

                }
            }
        }

        post {
            always {
                // Archive the Cucumber report
                archiveArtifacts artifacts: 'target/cucumber-reports/**/*.json', fingerprint: true

                 // Publish the Cucumber report
                 cucumberReport()
                }
            }
    }
}

def cucumberReport() {
    // Assuming you are using the Cucumber Reports Plugin
    cucumber {
        fileIncludePattern = '**/cucumber.json' // Adjust if necessary
        jsonReportDir = 'target/cucumber-reports/json' // Adjust to your directory structure
    }
}
