@Library('service-bridge-jenkins-shared-library') _

pipeline {
    agent any

    environment {
        BRANCH = 'main'
        CREDENTIALS_ID = 'github-security-passcode'
        REPO_URL = 'https://github.com/MrDeyi/main-app.git'
    }

    tools {
        maven 'Maven:3.9.1'
    }

    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }

        stage("Clone Repo") {
            steps {
                cloneRepo(BRANCH, CREDENTIALS_ID, REPO_URL)
            }
        }

        stage("Trigger Test Pipeline") {
            steps {
                dir('Main_app') {
                    sh 'mvn -Dtest=CucumberTestRunner test'
                }
            }
        }
    }

    post {
        always {
            script {
                // Check if the target directory exists
                def targetDirExists = fileExists('Main_app/target')
                if (targetDirExists) {
                    // Archive the HTML and JSON reports directly from the target directory within Main_app
                    archiveArtifacts artifacts: 'Main_app/target/*.{html,json}', fingerprint: true

                    // Publish the Cucumber report
                    cucumberReport()
                } else {
                    echo 'Target directory does not exist. Skipping artifact archiving and report publishing.'
                }
            }
        }
    }
}

def cucumberReport() {
    // Publish the Cucumber report from the correct directory
    cucumber(
        fileIncludePattern: '**/cucumber.json', // Pattern to find the JSON report
        jsonReportDir: 'Main_app/target' // Specify that the JSON report is in the target directory
    )
}
